"use client";

import {
  Activity,
  Bot,
  CalendarDays,
  FolderGit2,
  GaugeCircle,
  GitCompareArrows,
  GitPullRequest,
  Layers,
  LayoutGrid,
  Milestone,
  PieChart as PieIcon,
  Sparkles,
  Timer,
  TrendingUp,
  Users,
  Waypoints,
} from "lucide-react";
import type { WidgetType } from "@khove/shared";
import type { WidgetDef, WidgetProps } from "@/components/dashboard/widget-types";
import { KpiRow } from "@/components/dashboard/widgets/kpi-row";
import {
  AgentProposalsWidget,
  AiWeeklyReportWidget,
  CalendarAgendaWidget,
  CrossActivityWidget,
  CrossGapsWidget,
  CrossThreadsWidget,
  GithubCycleTimeWidget,
  GithubMilestonesWidget,
  GithubPrPipelineWidget,
  GithubReposWidget,
  GithubReviewLoadWidget,
  GithubThroughputWidget,
  JiraEpicsWidget,
  JiraSprintBurndownWidget,
  JiraStatusDistributionWidget,
  JiraVelocityWidget,
  KpiSingleWidget,
} from "@/components/dashboard/widgets";

// Adapter: the hero KPI strip is `KpiRow({provider, windowDays})`; wrap it in the
// widget contract so it can live on a dashboard as `kpi.row`.
function KpiRowWidget({ settings }: WidgetProps) {
  const provider = (settings.provider as "github" | "jira" | "all") ?? "all";
  const windowDays = (settings.windowDays as number) ?? 28;
  return <KpiRow provider={provider} windowDays={windowDays} />;
}

const PROVIDER_FIELD = {
  key: "provider",
  label: "Source",
  kind: "select" as const,
  options: [
    { value: "all", label: "All tools" },
    { value: "github", label: "GitHub" },
    { value: "jira", label: "Jira" },
  ],
  default: "all",
};

const WINDOW_FIELD = {
  key: "windowDays",
  label: "Window",
  kind: "select" as const,
  options: [
    { value: 14, label: "2 weeks" },
    { value: 28, label: "4 weeks" },
    { value: 56, label: "8 weeks" },
    { value: 84, label: "12 weeks" },
  ],
  default: 28,
};

export const WIDGET_REGISTRY: Record<WidgetType, WidgetDef> = {
  "kpi.row": {
    type: "kpi.row",
    title: "KPI overview",
    description: "Headline metrics with period-over-period deltas and sparklines.",
    category: "KPI",
    icon: LayoutGrid,
    component: KpiRowWidget,
    defaultSize: { w: 12, h: 2 },
    minW: 4,
    minH: 2,
    maxW: 12,
    maxH: 3,
    settingsSchema: [PROVIDER_FIELD, WINDOW_FIELD],
  },
  "kpi.single": {
    type: "kpi.single",
    title: "Single KPI",
    description: "One headline metric with its trend.",
    category: "KPI",
    icon: GaugeCircle,
    component: KpiSingleWidget,
    defaultSize: { w: 3, h: 2 },
    minW: 2,
    minH: 2,
    maxW: 6,
    maxH: 3,
    settingsSchema: [
      PROVIDER_FIELD,
      WINDOW_FIELD,
      {
        key: "metricKey",
        label: "Metric",
        kind: "select",
        options: [
          { value: "throughput", label: "Throughput / wk" },
          { value: "merged", label: "Merged / Completed" },
          { value: "cycle", label: "Cycle time" },
          { value: "review", label: "Review latency" },
          { value: "opened", label: "Opened" },
          { value: "deploy", label: "Deploys / wk" },
          { value: "points", label: "Points done" },
        ],
        default: "throughput",
      },
    ],
  },
  "github.prPipeline": {
    type: "github.prPipeline",
    title: "PR pipeline",
    description: "Open pull requests by review / CI state.",
    category: "GitHub",
    icon: GitPullRequest,
    component: GithubPrPipelineWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 3,
    maxW: 6,
    maxH: 5,
  },
  "github.throughput": {
    type: "github.throughput",
    title: "GitHub throughput",
    description: "Merged PRs per week.",
    category: "GitHub",
    icon: TrendingUp,
    component: GithubThroughputWidget,
    defaultSize: { w: 6, h: 3 },
    minW: 4,
    minH: 2,
    maxW: 12,
    maxH: 4,
  },
  "github.cycleTime": {
    type: "github.cycleTime",
    title: "GitHub cycle time",
    description: "Median open→merge time per week.",
    category: "GitHub",
    icon: Timer,
    component: GithubCycleTimeWidget,
    defaultSize: { w: 6, h: 3 },
    minW: 4,
    minH: 2,
    maxW: 12,
    maxH: 4,
  },
  "github.reviewLoad": {
    type: "github.reviewLoad",
    title: "Review load",
    description: "Open PRs awaiting each reviewer.",
    category: "GitHub",
    icon: Users,
    component: GithubReviewLoadWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 2,
    maxW: 6,
    maxH: 5,
  },
  "github.milestones": {
    type: "github.milestones",
    title: "Milestones",
    description: "GitHub milestone progress.",
    category: "GitHub",
    icon: Milestone,
    component: GithubMilestonesWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 2,
    maxW: 8,
    maxH: 6,
  },
  "github.repos": {
    type: "github.repos",
    title: "Repositories",
    description: "Repo activity — open PRs and issues.",
    category: "GitHub",
    icon: FolderGit2,
    component: GithubReposWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 2,
    maxW: 8,
    maxH: 6,
  },
  "jira.sprintBurndown": {
    type: "jira.sprintBurndown",
    title: "Sprint burndown",
    description: "Active sprint remaining vs ideal.",
    category: "Jira",
    icon: Activity,
    component: JiraSprintBurndownWidget,
    defaultSize: { w: 6, h: 4 },
    minW: 4,
    minH: 3,
    maxW: 12,
    maxH: 5,
  },
  "jira.velocity": {
    type: "jira.velocity",
    title: "Velocity",
    description: "Committed vs completed points per sprint.",
    category: "Jira",
    icon: TrendingUp,
    component: JiraVelocityWidget,
    defaultSize: { w: 6, h: 3 },
    minW: 4,
    minH: 2,
    maxW: 12,
    maxH: 4,
  },
  "jira.epics": {
    type: "jira.epics",
    title: "Epics",
    description: "Epic completion progress.",
    category: "Jira",
    icon: Layers,
    component: JiraEpicsWidget,
    defaultSize: { w: 4, h: 4 },
    minW: 3,
    minH: 2,
    maxW: 8,
    maxH: 6,
  },
  "jira.statusDistribution": {
    type: "jira.statusDistribution",
    title: "Issue status",
    description: "Jira issues by status category.",
    category: "Jira",
    icon: PieIcon,
    component: JiraStatusDistributionWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 3,
    maxW: 6,
    maxH: 5,
  },
  "cross.activity": {
    type: "cross.activity",
    title: "Activity",
    description: "Cross-tool event timeline.",
    category: "Cross-tool",
    icon: Activity,
    component: CrossActivityWidget,
    defaultSize: { w: 4, h: 4 },
    minW: 3,
    minH: 3,
    maxW: 8,
    maxH: 8,
  },
  "cross.gaps": {
    type: "cross.gaps",
    title: "Delivery gaps",
    description: "Where code and tickets are out of sync.",
    category: "Cross-tool",
    icon: GitCompareArrows,
    component: CrossGapsWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 2,
    maxW: 8,
    maxH: 6,
  },
  "cross.threads": {
    type: "cross.threads",
    title: "Threads",
    description: "Connectivity threads across your tools.",
    category: "Cross-tool",
    icon: Waypoints,
    component: CrossThreadsWidget,
    defaultSize: { w: 4, h: 4 },
    minW: 3,
    minH: 2,
    maxW: 8,
    maxH: 8,
  },
  "calendar.agenda": {
    type: "calendar.agenda",
    title: "Agenda",
    description: "Your upcoming meetings.",
    category: "Calendar",
    icon: CalendarDays,
    component: CalendarAgendaWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 2,
    maxW: 8,
    maxH: 8,
  },
  "agent.proposals": {
    type: "agent.proposals",
    title: "Agent proposals",
    description: "Pending agent actions awaiting approval.",
    category: "Agent",
    icon: Bot,
    component: AgentProposalsWidget,
    defaultSize: { w: 4, h: 3 },
    minW: 3,
    minH: 2,
    maxW: 8,
    maxH: 6,
  },
  "ai.weeklyReport": {
    type: "ai.weeklyReport",
    title: "Weekly AI update",
    description: "An AI-written status report on demand.",
    category: "AI",
    icon: Sparkles,
    component: AiWeeklyReportWidget,
    defaultSize: { w: 4, h: 4 },
    minW: 3,
    minH: 3,
    maxW: 8,
    maxH: 8,
  },
};

export const WIDGET_CATALOG: WidgetDef[] = Object.values(WIDGET_REGISTRY);
